Handle AR background with multiple polarization modes
delmic/odemis pull request #1528
Opened 2020-10-12 14:41 UTC by VictoriaDel

2020-10-13 08:32 UTC, Sabrina85 approved these changes
Looks good! 
Did you also check if we have a test case for this?
Reading my code here again, I see that there was a mistake in it (I guess that is why you updated the code :D ), which I think could have been caught by a proper test.

2020-10-13 08:32 UTC, Sabrina85 commented on src/odemis/acq/calibration.py
> +    # expect the worse: multiple AR data (per polarization mode)
worse -> worst

2020-10-13 09:09 UTC, pieleric commented
Victoria, could you have a look at the test cases, as suggested by Sabrina? I had a quick look at them, and I guess we broke the arpol test case, as it specifically checks that the returned arrays are in the same order (which is not anymore the case with the user of the dict, and not needed). I guess that changing to `self.assertEqual(set, set)` should solve this.

Also, could you add another test case, which check that only one AR data is returned when passing several AR data (without polarization mode).

2020-10-19 13:51 UTC, pieleric requested changes
I'd recommend to do the checks a different way.

2020-10-19 13:51 UTC, pieleric commented on src/odemis/acq/test/calibration_test.py
> +        self.assertEquals(bg_list, out_list, msg="compare lists ignoring the order")
I don't understand how this works, as this is still a list, so it still has a problem with the order. 
I'd recommend something like:
```python
# Check the expected and return lists contain the same DataArrays
self.assertEqual(len(bg_data), len(out))
for da in out:
    self.assertIn(da, bg_data)
```

2020-10-19 13:51 UTC, pieleric commented on src/odemis/acq/test/calibration_test.py
> +from odemis.acq.stream import POL_POSITIONS, MD_POL_VERTICAL
`MD_POL_VERTICAL ` doesn't seem used, is it?

2020-10-22 11:56 UTC, merged