Update "Setting up a data analysis environment on Windows" (section 2.3.2)
delmic/odemis pull request #1678
Opened 2021-02-18 16:03 UTC by VictoriaDel

2021-02-24 16:41 UTC, pieleric requested changes

2021-02-24 20:22 UTC, VictoriaDel commented on doc/develop/extending.rst
> +Note that you may need to navigate to the Documents/Odemis/src folder to be able to import from odemis.
Yes indeed but this did happen in both VMs. I tried to import odemis in the spyder console and it didn't work. Then I realized I had to give the path. If I am not mistaken only when I activate and run spyder in the command prompt, I don't need to give the path.

2021-02-25 13:11 UTC, VictoriaDel commented on doc/develop/extending.rst
> +      that the spyder kernel version is smaller than 1.10.0.
I just wanted to explain what the command does but it's better to delete this sentence. The command itself already tells a lot about the spyder kernel version.

2021-03-05 23:01 UTC, pieleric requested changes
Just a tiny typo, and it'll be fine.

2021-03-08 08:05 UTC, merged