Updated spot-grid.py script
delmic/odemis pull request #1709
Opened 2021-03-23 12:51 UTC by effting

- Supports to load image from command line
- Indicator of first spot in the image
- 'Snake' to indicate order of spots

2021-03-23 14:17 UTC, pieleric requested changes

2021-03-23 14:17 UTC, pieleric commented on scripts/spot-grid.py
> +    def __init__(self, filename):
Please take a DataArray as input. Let's separate reading away.

2021-03-23 14:17 UTC, pieleric commented on scripts/spot-grid.py
> +        super(StaticImageComponent, self).__init__(name=filename, role='ccd')
As name, just hard code to something like: "FakeCCD".

2021-03-23 14:17 UTC, pieleric commented on scripts/spot-grid.py
> +        image = StaticImageComponent(options.filename)
Let's rename image -> fakeccd.

2021-03-23 14:17 UTC, pieleric commented on scripts/spot-grid.py
> +        logging.info("Will process image file %s" % options.filename)
To open the file, you can do it without skimage, just with what we already have in Odemis. You can write:
``` python
    converter = dataio.find_fittest_converter(fn, default=None, mode=os.O_RDONLY)
    data = converter.read_data(filename)
    image = data[0]
```

2021-03-23 14:17 UTC, pieleric commented on scripts/spot-grid.py
> +class StaticImageComponent(model.DigitalCamera):
Can you rename it to StaticCCD?

2021-03-23 14:17 UTC, pieleric commented on scripts/spot-grid.py
> +import skimage.io
So far we don't depend on skimage. Let's try to not depend on it. If you need more than TIFF + HDF5, you could have a look at Pillow (which we already depend on).

2021-03-25 14:50 UTC, pieleric approved these changes

2021-03-26 10:13 UTC, tepals approved these changes

2021-03-26 12:35 UTC, merged