driver technolution: minor improvements in acquisition
delmic/odemis pull request #1766
Opened 2021-05-14 14:43 UTC by pieleric

2021-05-14 15:04 UTC, tepals requested changes

2021-05-19 12:15 UTC, Kleijwegt commented on src/odemis/driver/test/technolution_test.py
>          print("image received")
That was usefull when debugging/building the acquisition thread. But maybe now it is redundant.

2021-05-19 12:16 UTC, Kleijwegt approved these changes
I had a quick look and these changes look good to me.

2021-05-20 15:12 UTC, pieleric commented on src/odemis/driver/test/technolution_test.py
> +from odemis.driver.technolution import AcquisitionServer, convert2Bits, convertRange, AsmApiException, DATA_CONTENT_TO_ASM
It's a bit of a pain, as PyDev automatically order it this way, but I really don't understand its logic. 
I've moved it back to were it was, as I didn't really touch this line anyway. Not that I think the previous place was logical either ;-)

2021-05-20 15:13 UTC, pieleric commented on src/odemis/driver/test/technolution_test.py
>          print("image received")
I've changed them to logging.info(). It can still be useful in case of test failure.

2021-05-20 15:15 UTC, pieleric commented on src/odemis/driver/test/technolution_test.py
> +        # The implementation supports sending multiple next in a raw, and they
It means "in a row"... in a raw English ;-)
Thanks for catching all my stupid English errors!

2021-05-21 07:17 UTC, tepals approved these changes

2021-05-21 13:14 UTC, merged