acq stitching tiledacq: add registrar and weaver arguments
delmic/odemis pull request #1770
Opened 2021-05-20 14:34 UTC by pieleric

These argument allow to adjust the exact behaviour of the tiling.
In particular, in some case we want to tile without overlap (because the
stage precisition is good enough). In such case, the default registrar
would get confused/sad. It'd fallback to IDENTITY, but generate a lot of
warnings on the way.

2021-05-21 13:17 UTC, lazem approved these changes

2021-05-21 14:50 UTC, pieleric commented
I hadn't properly tested the changes. This new version seems to really work, at least on the simulator. Please @lazem, have a second look.

2021-05-21 20:36 UTC, lazem commented
> I hadn't properly tested the changes. This new version seems to really work, at least on the simulator. Please @lazem, have a second look.

Sure @pieleric I will have a deeper look.

2021-05-25 10:30 UTC, lazem requested changes
Looks good, I suggest one small change to the test.

2021-05-25 10:30 UTC, lazem commented on src/odemis/acq/stitching/test/tiledacq_test.py
> +        area = (0, 0, 0.00001, 0.00001)
This area is smaller than the fov, so it only stitches 1 image. Suggest to change it to:
```
sem_fov = compute_scanner_fov(self.ebeam)
area = (0, 0, sem_fov[0], sem_fov[1])
```

2021-06-07 08:28 UTC, lazem approved these changes

2021-06-07 08:53 UTC, merged