driver-piezomotor: document behaviour of open-loop simulator
delmic/odemis pull request #1774
Opened 2021-05-25 13:44 UTC by philipwinklerdelmic

Currently, the position returned by the simulator is always 0 in open-loop. This might be the same behaviour as on the hardware if no encoder is connected (should be checked!)

2021-05-25 14:28 UTC, tepals reviewed
I think it's fine like this, do you think it makes sense to add a closed loop test that does check the position?
Just a simple:
```
pos_x = 0.01
f = self.stage.moveAbs({'x': pos_x})
f.result()
self.assertEqual(self.stage.position["x"], pos_x)
```

2021-05-27 20:46 UTC, pieleric requested changes
I'm not very convinced by these changes: it's mostly asking questions. It'd be more useful to put these questions in a Jira task, then to a 1 hour remote connection to the system, and find out. Then you can actually put the answers in the code ;-)

2021-06-14 10:11 UTC, philipwinklerdelmic commented
@tepals Do you think it's important enough to investigate? Since it's just a question for the simulator and only for the open-loop (which we don't use anyway), I think we can just drop the issue. Otherwise, I can make a jira-task (not sure though when anybody has time to look into this).

2021-06-14 11:06 UTC, tepals commented
I think we can drop it

2021-06-14 11:07 UTC, closed without merging