technolution_acqHandling
delmic/odemis pull request #1811
Opened 2021-06-29 08:44 UTC by Sabrina85

2021-06-29 12:04 UTC, pieleric requested changes

2021-07-02 09:49 UTC, Sabrina85 commented on src/odemis/driver/test/technolution_test.py
>                  # Allow 1.5 seconds per field image to be acquired
The waiting is not needed for the offloading as field images to be offloaded are simply queued on the ASM. I think this waiting here is actually really for waiting that the field image to be acquired is finished and the subscribers are notified. Or do I miss something?

2021-07-02 10:07 UTC, Sabrina85 commented on src/odemis/driver/technolution.py
> +                    notifier_func = args[1]  # Return function (usually, dataflow.notify or acquire_single_field queue)
Is this typical to actually put a method in the args instead of the queue itself and then call the queue.put() here in the thread?

2021-07-05 12:39 UTC, pieleric commented on src/odemis/driver/test/technolution_test.py
>                  # Allow 1.5 seconds per field image to be acquired
OK... fine, then just update the comment to say "allow 3 seconds".

2021-07-05 12:42 UTC, pieleric commented on src/odemis/driver/technolution.py
> +                    notifier_func = args[1]  # Return function (usually, dataflow.notify or acquire_single_field queue)
There is nothing typical. I've never seen before putting a queue as (sub)element of a queue. Neither have I seen passed a function to "answer" the queue message.
As we are using a function in the case of a "next", I think it's best to use the same mechanism for the "start", to keep things similar. However, the comment says "actually the function will be dataflow.notify, which is incorrect here). So please update the comment.

2021-07-08 13:41 UTC, pieleric approved these changes
Looks fine.
How should we merge it? Can I squash all the commits together, or do you want to merge back your fixes into the some of the 4 commits you had neatly made?

2021-07-08 14:26 UTC, Sabrina85 commented
I don't mind. Last time there was the request to separate the style related changes from actual code changes. So I can try to merge the updates into the commits if you like.

2021-07-08 14:38 UTC, pieleric commented
Ok, give a short try. If you encounter any difficulty, don't bother too long, and we'll just squash everything. 
It's useful to have separate commits for different aspects, but the main use is for reviewing... so once it's reviewed, it's less useful. (it's also useful when fixing bug that should be backported).

2021-07-09 07:32 UTC, Sabrina85 commented
I squashed everything. I would have needed to split up the update commits themselves. So I didn't go for it. Ready to merge I think.

2021-07-09 08:00 UTC, merged