fastem gui: add alignment button to acquisition tab
delmic/odemis pull request #1833
Opened 2021-07-21 08:27 UTC by philipwinklerdelmic

2021-07-27 14:46 UTC, philipwinklerdelmic commented
Updated to show label on the right

2021-08-02 13:23 UTC, pieleric requested changes

2021-08-02 13:23 UTC, pieleric commented on src/odemis/gui/model/__init__.py
> +        self.is_aligned = model.BooleanVA(False)
Eventually, this should it automatically be reset whenever the user pumps the chamber. Even turning off/on the e-beam? Other cases? Do you have already plans to add these? Maybe you can already do some of it in this PR.

2021-08-02 13:23 UTC, pieleric commented on src/odemis/gui/cont/acquisition.py
> +        self._panel.Parent.Layout()
Are you sure that `self._panel.Layout()` is not sufficient? I don't get why you have you force the layout of the parent (but I know that wxWidgets is sometimes strange about this).

2021-08-02 13:23 UTC, pieleric commented on src/odemis/gui/cont/acquisition.py
> +            logging.error("Cancelling alignment currently not supported.")
Let's add a TODO. (or otherwise, don't call this button "Cancel")

2021-08-02 13:23 UTC, pieleric commented on src/odemis/gui/cont/acquisition.py
> +        self._is_aligning = True
Shouldn't more things be disabled in the GUI? I guess it wouldn't be a good idea to move the stage, or change the tab and start an overview acquisition during alignment. => Set the `is_acquiring` VA of the MainGUIData?

2021-08-09 07:42 UTC, philipwinklerdelmic commented
Pushed changes.

2021-09-06 10:03 UTC, pieleric approved these changes

2021-09-06 10:03 UTC, merged