futures: batch future for time estimates of multiple ProgressiveFutures
delmic/odemis pull request #1858
Opened 2021-09-01 14:33 UTC by philipwinklerdelmic

Also updated fastem acquisition to show the correct progress. Some considerations:

* I use a dict as an argument. Alternatively, a list of tuples might be possible to give the futures in order. However, this class also works independent of the order in which futures are started (future can run in parallel), so it doesn't matter.
* The regular ProgressiveFuture always raised a warning (starttime > endtime) every time a future was started after the expected endtime. Since many futures are initialized without endtime, the current time is used for both starttime and endtime, but if the future is started later (because the executor first had to finish another future), the starttime would update to a higher value, while the endtime remained the same (a value that is now in the past). That should be fixed now.
* ProgressiveFutures are in general not very easy to use with executors because we don't know when they are going to start. Instead of start and end arguments, it might make sense to change the interface to start and time_estimate arguments. But that would involve a larger change in odemis. We can discuss if it's a good idea. It would also make the BatchFuture interface easier because we wouldn't need the expected time dictionary as argument.

2021-09-06 11:43 UTC, philipwinklerdelmic commented on src/odemis/model/_futures.py
> +        self.set_progress(end=self._estimate_end())
I did this before, but somehow, there is still a progress update after the future is done and in the update callback I change the estimate again to a positive value. This is why I prefer to just ignore all future that are done.

2021-09-17 11:06 UTC, pieleric requested changes

2021-09-17 11:06 UTC, pieleric commented on src/odemis/model/_futures.py
> +        except CancelledError:
What case are you handling? When .cancel() was just called, and so the (sub-)future is cancelled?  Is that really how it'll happen? I'd expect that in such case `ex` contains a CancelledError, but it'd would not be raised. Or is it that .cancel() would raise CancelledError in such case? If so, please indicate in a comment.

2021-09-21 12:36 UTC, philipwinklerdelmic commented
pushed changes

2021-09-24 15:55 UTC, pieleric requested changes
There is still one comment to add. Otherwise, it looks fine.

2021-09-27 09:41 UTC, philipwinklerdelmic commented
What comment do you want me to put? I added "raises CancelledError if cancelled, otherwise returns error" in line 526.

2021-09-27 15:38 UTC, merged