Fastem acquisition manager: added method to correct the beamshift for…
delmic/odemis pull request #1979
Opened 2021-12-29 15:48 UTC by tepals

… the paramagnetic field changes in between single field acquisitions.

Added beamshift and diagnostic-ccd to MainGUIData

I've tested that it runs, I haven't tested that it's actually doing the correct thing yet.

2021-12-30 09:23 UTC, Sabrina85 requested changes

2022-01-03 09:30 UTC, tepals commented on src/odemis/gui/model/__init__.py
> +        self.beamshift = None  # beam shift deflection controller
diagnostic-ccd is mapped to ccd, since `self.ccd` is already initialized here there is no need to add it

2022-01-04 08:40 UTC, tepals commented on src/odemis/acq/fastem.py
> +            self.correct_beam_shift()  # correct the shift of the beams caused by the paramagnetic field.
I quickly discussed with Wilco and he wants it on the previously imaged field, however it's a bit more complicated when you start a new field. So for now I will leave it like this and I've created an issue to implement it on the previous field. https://delmic.atlassian.net/browse/SDEV-1001

2022-01-04 09:23 UTC, tepals commented on src/odemis/acq/fastem.py
> +        shift = numpy.mean(spot_coordinates, axis=0) - good_mp_position  # [px]
This needs to be tested, it was implemented like this in the acquisition script, but maybe that was incorrect.

2022-01-05 14:58 UTC, Sabrina85 reviewed
It looks good! If you can think about a test for the beamshift, that would be nice to have. But I don't know if that is possible. Maybe something where you define the good position and move the stage off by a defined value, would it then be possible to find the shift (within the accuracy of the stage) and check it is corrected in the right direction and by the right abs value? Didn't think it completely through, though.

2022-01-06 13:25 UTC, Sabrina85 approved these changes
Agreed to add the test cases after changing the behavior to perform the beamshift correction on the previous image.

2022-01-06 13:27 UTC, merged