gui: improve keyboard control
delmic/odemis pull request #2018
Opened 2022-02-01 13:15 UTC by pieleric

2022-02-02 12:03 UTC, Sabrina85 requested changes

2022-02-08 09:50 UTC, pieleric commented on src/odemis/gui/comp/canvas.py
> +            return
It's not per se something for the docstring. All event handlers follow more or less the same behaviour. However, here, when we find that the user pressed a key which we are interested in (and process) we have to indicate this key is officially handled, by immediately returning (and not letting other code process it further). I've added a comment.

2022-02-08 10:03 UTC, pieleric commented on src/odemis/gui/comp/viewport.py
> +        ord("+"):-0.1,
Yes, you understood correctly. I've add some extra comments.

2022-02-08 10:07 UTC, pieleric commented on src/odemis/gui/comp/viewport.py
> +            if evt.ShiftDown():  # softer
No, we don't support increasing the stepsize. For the value inputs, we do support it (with Ctrl), but typically Ctrl+KEY is for shortcuts, so it's a little tricky to use Ctrl in every case. So for now we don't support it. No one ever asked for it either...

2022-02-08 10:11 UTC, pieleric commented on src/odemis/gui/comp/viewport.py
> +            shift = (rng[1] - rng[0]) * move
I've added a docstring which should summarize this.

2022-02-08 10:13 UTC, pieleric commented on src/odemis/gui/comp/viewport.py
> +        """ Scroll event for the bottom legend.
Yes. That's the .bottom_legend attribute of the object.

2022-02-08 10:18 UTC, pieleric commented on src/odemis/gui/comp/viewport.py
> +        scale = -0.1 * rot
0.1 means 10% of the range, like for the key press. I've added a comment.

2022-02-08 10:21 UTC, pieleric commented on src/odemis/gui/comp/viewport.py
> +        zoom_centre = self.canvas.pos_x_to_val_x(evt.Position[0])
Well, the goal is to zoom with the position under the mouse staying fixed. So we set the current mouse position as the "zoom centre".

2022-02-08 10:22 UTC, pieleric commented on src/odemis/gui/comp/viewport.py
> +        """ Scroll event for the left legend.
The left legend is the y-axis. It's already indicate in the line just below.

2022-02-08 10:28 UTC, pieleric commented on src/odemis/gui/comp/viewport.py
> +        Move the horizontal range. The range always stays within safe values.
"range" is what defines the min and max value seen in the plot. The class uses this concept all around. See the .hrange and .vrange VAs. I'll keep the names as it is.
By "safe value" I meant a value which is within the complete data range. I've updated the comment.

2022-02-08 14:26 UTC, pieleric commented on src/odemis/gui/comp/viewport.py
> +        self.hrange_lock.value = True  # disable autoscaling when the user zooms in
Autoscaling of the range.

2022-02-08 14:37 UTC, pieleric commented on src/odemis/gui/comp/viewport.py
> +        # Clamp the ranges - this functions differently for scrolls than pans
I now simplified and just explain separately in each function how we define the min/max values.

2022-02-08 14:42 UTC, pieleric commented on src/odemis/gui/comp/viewport.py
> +        prop = (centre - rng[0]) / span
Is it clearer to say "relative position of the centre"?

2022-02-08 15:05 UTC, pieleric commented on src/odemis/gui/comp/viewport.py
> +        shift (float): amount to shift, in range units
That's the unit of the range, whichever that unit is. Updated the doc to be slightly clearer. If you can suggest a better way to describe that, I would welcome it!

2022-02-08 15:06 UTC, pieleric commented on src/odemis/gui/comp/viewport.py
> +        # Move the horizontal axis
That's a left over comment. It's now replaced by the function name...

2022-02-08 15:08 UTC, pieleric commented on src/odemis/gui/comp/viewport.py
> +        self.hrange_lock.value = True  # disable autoscaling when the user drags the scale
Here the scale meant the "legend". That's confusing. I've changed to "the user pans around".

2022-02-08 19:56 UTC, Sabrina85 requested changes
It was really worth to put the effort in the documentation. It is now much easier to follow :) I reviewed the last 3 commits. Let me know if I need to also look at the first 3 as there was a force push.

2022-02-08 19:56 UTC, Sabrina85 commented on src/odemis/gui/comp/viewport.py
>          if evt.ShiftDown():  # softer
Can you add here similar to the above comments, that this means "smaller zoom"?

2022-02-08 19:56 UTC, Sabrina85 commented on src/odemis/gui/comp/viewport.py
> +        zoom_centre = self.canvas.pos_x_to_val_x(evt.Position[0])
Good that we have a comment now to clarify then :)

2022-02-08 19:56 UTC, Sabrina85 commented on src/odemis/gui/comp/viewport.py
> +        prop = (centre - rng[0]) / span
Yes that sounds better. Can you add `relative position of the center in respect to xxxx` ?

2022-02-08 19:56 UTC, Sabrina85 commented on src/odemis/gui/comp/viewport.py
> +        self.hrange_lock.value = True  # disable autoscaling when the user zooms in
Is that similar to the auto button we have for auto BC?

2022-02-11 21:09 UTC, Sabrina85 approved these changes
I approve the pr now as I am on holiday and it looked already good. I had only 2 small comments anyways.

2022-02-15 17:03 UTC, pieleric commented on src/odemis/gui/comp/viewport.py
> +        self.hrange_lock.value = True  # disable autoscaling when the user zooms in
Sort-of. It's a "lock" button. You can test it by loading a spectrum test data in the Odemis viewer.

2022-02-15 22:00 UTC, merged