Acquisition tests: skip test cases that require the nikonc driver.
delmic/odemis pull request #2097
Opened 2022-03-31 12:45 UTC by tepals

The nikonc driver is not easily available for python3. When tests were run that required this driver the backend failed to start. In the setupclass it is now checked if the driver is available and otherwise the tests are skipped

2022-04-01 12:28 UTC, Kleijwegt approved these changes

2022-04-01 13:12 UTC, pieleric requested changes

2022-04-01 13:12 UTC, pieleric commented on src/odemis/acq/test/flim_test.py
> +            # The nikonc driver only works for python2.
No, that's not really true. Let's write "The nikonc driver needs omniorb which is not packaged in Ubuntu anymore".

2022-04-06 11:31 UTC, pieleric approved these changes

2022-04-12 08:56 UTC, merged