Fix pytest log filter
delmic/odemis pull request #2242
Opened 2022-10-17 14:52 UTC by tepals

In commit 25fe610fbf532ab5097f91e9d65ec5298a7bbfdf the log filter was updated to include the short test summary. It was only tested on ubuntu 18.04, where the 'short test summary' is at the beginning of the log. In Ubuntu 20.04 the 'short test summary' is at the end, therefore everything was filtered out except for the 'short test summary'. Additionally this commit makes sure that when the message is too long it is cut up into 20 complete lines, instead of the first 1000 characters of the log.

2022-10-17 14:58 UTC, pieleric approved these changes

2022-10-25 07:43 UTC, BasHolweg approved these changes

2022-10-25 07:46 UTC, pieleric requested changes

2022-10-25 07:46 UTC, pieleric commented on util/pytest_log_filter.py
It'd help have an explicit `else: return None` here. I hadn't noticed beforehand that the function can return None!

2022-10-25 08:21 UTC, pieleric approved these changes

2022-11-01 14:53 UTC, merged