runtests update to only show the short test summary info in the test …
delmic/odemis pull request #2264
Opened 2022-11-21 13:54 UTC by tepals

…summary file

The test summary used to show anything accept the passed test cases. Because there are a lot of warnings and logs the test summary per module was often more than 40 lines long and then the middle part was cut out. This resulted in some of the failures being cut out of the summary as well. From now on we only show the short test summary in the summary file. This contains one line per failed test case. There is no cutting in the summary anymore, so even if there are more than 40 fails,they will still all be shown. The summary for each test module starts with 'Running ....', with the filepath of the test module on the dots.

The example test output from ubuntu 20.04 started with the wrong line, so that line was removed.

2022-11-25 15:38 UTC, tepals commented on util/pytest_log_filter.py
> +def filter_test_log(log_txt, filter_type='summary'):
add `filter_type` to docstring

2022-11-25 15:38 UTC, tepals commented on util/test/test_pytest_log_filter.py
>      def test_sample_input_ubuntu_18_04(self):
update tests for warnigns

2022-11-25 16:39 UTC, pieleric requested changes

2022-11-28 11:01 UTC, K4rishma commented on util/pytest_log_filter.py
>      :return (str): filtered log, returns None if there is nothing interesting in log_txt
```suggestion
    :return: (str) filtered log, returns None if there is nothing interesting in log_txt
```

2022-11-28 13:18 UTC, BasHolweg approved these changes

2022-11-28 14:51 UTC, pieleric approved these changes

2022-11-28 16:16 UTC, K4rishma approved these changes

2022-11-28 16:19 UTC, merged