fix failing test cases
delmic/odemis pull request #2286
Opened 2022-12-13 09:27 UTC by FCanberk

fixed 5 failing test cases under `class ProxyOfProxyTest(unittest.TestCase):`

set the `BASE_DIRECTORY` using `tempfile.gettempdir()` to ensure the folder exist on both windows and linux operating systems.

2022-12-13 09:36 UTC, tepals commented on src/odemis/model/_core.py
> +BASE_DIRECTORY = tempfile.gettempdir() + "/odemisd"
to make it completely os independent you should use:
```
BASE_DIRECTORY = os.path.join(tempfile.gettempdir(), "odemisd")
```

2022-12-13 09:38 UTC, tepals commented on src/odemis/model/_core.py
>  import Pyro4
If you want you could add another commit to update the import order according to the new coding guidelines and replace the `'''` with `"""` on line 2 and line 21

2022-12-13 10:01 UTC, tepals requested changes
few small extra comments

2022-12-13 12:08 UTC, pieleric requested changes

2022-12-13 12:26 UTC, pieleric requested changes

2022-12-13 12:26 UTC, pieleric commented on src/odemis/model/test/remote_test.py
> +        comp2.unsub()
This should not be uncommented. It's to show where the unsub() call would be happening, but it's not happening and still things should work.... What you can do is to add a comment explaining that.

2022-12-29 13:11 UTC, tepals approved these changes

2023-01-20 11:59 UTC, merged