Sdev1248 fix starting calibration without region
delmic/odemis pull request #2309
Opened 2023-01-19 15:27 UTC by tepals

2023-01-20 08:30 UTC, pieleric requested changes

2023-01-20 08:30 UTC, pieleric commented on src/odemis/gui/cont/project.py
> +        self.regions_calib_3 = getattr(tab_data, "regions_calib_3")
I think this comes from copying the code of `FastEMROCController`, as there is multiple calibrations, it'd be difficult, and anyway, if it's always the same one, it doesn't really make sense to generalise it.
So you can drop the getattr too, like that:
```
self.regions_calib_3 = tab_data.regions_calib_3
```

2023-01-20 08:56 UTC, tepals commented on src/odemis/gui/cont/fastem_acq.py
> +        roc_available = any([
nice, I did not know that :)

2023-01-31 09:11 UTC, pieleric approved these changes

2023-01-31 09:22 UTC, nandishjpatel approved these changes

2023-01-31 13:28 UTC, merged