Partial grid estimation
delmic/odemis pull request #2325
Opened 2023-02-05 21:26 UTC by effting

Updates to `odemis.util.registration` to improve estimation of grid orientation in case of an incomplete grid.

2023-02-10 13:28 UTC, tepals requested changes

2023-02-10 14:29 UTC, effting commented on src/odemis/util/registration.py
> +from __future__ import annotations
Removed

2023-02-10 14:30 UTC, effting commented on src/odemis/util/registration.py
> +    def __neg__(self) -> WeightedShift:
Updated

2023-02-10 14:30 UTC, effting commented on src/odemis/util/registration.py
> +        # deprecated. For example it's not allowed to return a numpy.float64),
Thanks for catching!

2023-02-15 08:35 UTC, tepals approved these changes

2023-02-15 08:47 UTC, merged