fix for yaml.representer.RepresenterError raised exception when an ob…
delmic/odemis pull request #2351
Opened 2023-03-01 16:01 UTC by nandishjpatel

In the `self._persistent_data` dict for FAST-EM ['Mirror Descanner']['properties']['scanOffset'] is a tuple containing numpy.float64 elements.

This raises a yaml exception while dumping the dictionary. A work-around is inheriting yaml `SafeRepresenter` class and handling `numpy.float_` datatype by converting into float. Finally, `CustomSafeDumper` makes use of `CustomSafeRepresenter` and is used as the dumper during `yaml.dump()`.

2023-03-02 08:29 UTC, tepals requested changes

2023-03-02 08:29 UTC, tepals commented on src/odemis/odemisd/main.py
> +        self.represent_float(data)
can you add a comment to explain that this is because yaml does not support dumping numpy floats

2023-03-07 09:28 UTC, pieleric requested changes
This class would be a lot less lonely if it had a test case for it ;-)
See util.test.conversion_test.test_json_numpy() for inspiration.

2023-03-07 10:10 UTC, nandishjpatel commented
> This class would be a lot less lonely if it had a test case for it ;-) See util.test.conversion_test.test_json_numpy() for inspiration.

Haha, sure I can write a testcase :)

2023-03-09 16:08 UTC, pieleric approved these changes

2023-03-13 08:19 UTC, tepals approved these changes

2023-03-13 08:22 UTC, merged