small change to the plugins section of the odemis developer manual
delmic/odemis pull request #2439
Opened 2023-06-06 14:20 UTC by sneepstefan

The part of the plugin loaded when Odemis starts was not aligned with the SPARCv2 manual. Now these are more or less similar.

2023-06-06 15:05 UTC, tepals approved these changes

2023-06-08 16:03 UTC, pieleric requested changes

2023-06-09 07:54 UTC, sneepstefan commented on doc/develop/plugins.rst
> + * Linux: ``$HOME/.local/share/odemis/plugins/``
We could change that indeed but then the Dev Manual and the SPARCv2 Manual will not be aligned regarding the plugins section. We should update the SPARC manual then as well right?

2023-06-12 09:21 UTC, pieleric commented on doc/develop/plugins.rst
> + * Linux: ``$HOME/.local/share/odemis/plugins/``
I think that the user manual should just explain the standard way that a user should add a plugin. Nowhere in the manual it says that it's the *only* right way to do it. In contrary, in the developer manual it's convenient to be describing what the code does. Hence I think it's fine that they don't contain exactly the same information.

2023-06-12 09:22 UTC, pieleric approved these changes

2023-06-12 09:22 UTC, merged