fix H5pyDeprecationWarning: other_ds.dims.create_scale(ds, name) is d…
delmic/odemis pull request #2456
Opened 2023-06-22 10:11 UTC by nandishjpatel

…eprecated. Use ds.make_scale(name) instead with backwards compatibility for Ubuntu 18

2023-06-22 13:55 UTC, K4rishma approved these changes

2023-06-26 14:24 UTC, pieleric requested changes

2023-06-26 14:24 UTC, pieleric commented on src/odemis/dataio/hdf5.py
> +            if hasattr(dataset, "make_scale"):
Could you add at least at one place (ex, this line), when can we remove the `else` block? Indicate the first version of h5py which support this new function.

2023-06-29 14:54 UTC, pieleric approved these changes

2023-06-29 14:56 UTC, merged