wx.NewID() to wx.Window.NewControlId() fix
delmic/odemis pull request #2462
Opened 2023-06-22 12:39 UTC by K4rishma

src/odemis/gui/test/comp_stream_test.py::FoldPanelBarTestCase::test_add_stream
   /home/testing/development/odemis/src/odemis/gui/comp/buttons.py:1038: DeprecationWarning: NewId() is deprecated

2023-06-22 13:52 UTC, FCanberk approved these changes

2023-06-22 14:14 UTC, tepals approved these changes

2023-06-22 14:15 UTC, tepals requested changes
Can you update the commit message to state why you made this change?

2023-06-23 09:33 UTC, tepals approved these changes

2023-06-23 14:22 UTC, sneepstefan approved these changes

2023-06-26 07:50 UTC, merged