util pituner: add master option
delmic/odemis pull request #2466
Opened 2023-06-23 16:42 UTC by pieleric

Needed to work with the latest C885 controller, which now uses master = 1.

Also fix an issue in Python 3.

2023-06-26 07:36 UTC, tepals requested changes

2023-06-26 07:36 UTC, tepals commented on util/pituner
> +                         "Default is 254 if applicable.")
```suggestion
    parser.add_argument('--master', dest="master", type=int,
                        help="The address of the 'master' controller when connecting over "
                             "TCP/IP to multiple controllers. It is unused when connecting over serial port."
                             "Default is 254 if applicable.")
```

2023-06-27 07:37 UTC, tepals approved these changes

2023-06-27 07:54 UTC, sneepstefan approved these changes

2023-06-28 08:40 UTC, merged