added physical position in addition to pixel position for the PixelVa…
delmic/odemis pull request #2478
Opened 2023-07-04 13:23 UTC by nandishjpatel

…lueOverlay

2023-07-05 21:09 UTC, pieleric requested changes

2023-07-05 21:09 UTC, pieleric commented on src/odemis/gui/comp/overlay/view.py
> +            self._label.align = wx.ALIGN_RIGHT
This line is actually also always the same. So could you move it with the colour, line 319? (and also drop the line 338).

2023-07-06 08:38 UTC, nandishjpatel commented on src/odemis/gui/comp/overlay/view.py
> +        if self._v_pos:
```suggestion
        if self.v_pos:
```

2023-07-10 10:51 UTC, K4rishma approved these changes

2023-07-18 04:01 UTC, pieleric approved these changes

2023-07-18 04:25 UTC, merged