[add] tabs enabler plugin
delmic/odemis pull request #2482
Opened 2023-07-13 11:43 UTC by FCanberk

Add plugin to enable tabs and add the function to enable alignment tab on enzel, sparc, secom and mimas through "Enable alignment tab" button under Help > Development on the top bar.

2023-07-13 13:56 UTC, tepals requested changes

2023-07-13 13:56 UTC, tepals commented on plugins/tabs_enabler.py
> +Created on 10 April 2017
that's a long time ago :p

2023-07-13 13:56 UTC, tepals commented on plugins/tabs_enabler.py
> +another one (already present).
I think this needs to be updated

2023-07-18 06:40 UTC, pieleric requested changes

2023-07-18 06:40 UTC, pieleric commented on plugins/tabs_enabler.py
> +    __author__ = u"Canberk Akın"
You can (now) drop the `u` from the string.

2023-07-18 06:40 UTC, pieleric commented on plugins/tabs_enabler.py
> +        super(TabEnablerPlugin, self).__init__(microscope, main_app)
Now, you can just write:
```suggestion
        super().__init__(microscope, main_app)
```

2023-07-18 06:40 UTC, pieleric commented on plugins/tabs_enabler.py
> +        self.addMenu("Help/Development/Enable alignment tab", self.enable_alignment_tab)
Please only add this menu if it's possible to click this option. Especially, the viewer (which is also available on all the computers, and doesn't connect to the back-end). The simplest way is probably to do the same check as in `enable_alignment_tab()`: check whether `btn_tab_align_enzel` or `btn_tab_align` are shown.

2023-07-18 06:41 UTC, pieleric commented
Could you please follow the new convention for naming the PRs, and add the Jira task ID in the PR name.

2023-07-19 02:40 UTC, pieleric approved these changes

2023-07-19 11:19 UTC, tepals approved these changes

2023-07-19 11:22 UTC, merged