[fix] gui SPARC2 alignment tab: completly hide panels which cannot be used
delmic/odemis pull request #2506
Opened 2023-08-25 12:06 UTC by pieleric

Depending on the alignement mode, only some hardware axes can be moved.
Until now, the axes which couldn't be moved where disabled. However, on
systems with a lot of axes, that didn't fit in the window.

=> Just hide the controls which are not supposed to be used for each
given alignment mode.

2023-08-28 07:26 UTC, FCanberk approved these changes

2023-08-29 08:49 UTC, sneepstefan requested changes

2023-08-31 14:47 UTC, pieleric commented on src/odemis/gui/cont/tabs.py
> +            #self.panel.btn_manual_focus.Enable(True)
No, it should go away too!

2023-08-31 14:48 UTC, pieleric commented on src/odemis/gui/cont/tabs.py
> -            self.panel.btn_manual_focus.Enable(True)
Indeed, all of them where enabling it. We never need to disable it. So I just removed them.
Now it's only disabled while the autofocus is running, and it's automatically re-enabled afterwards. But all this has nothing to do with changing the alignment mode. This allows to keep this code simple.

2023-09-01 06:52 UTC, sneepstefan approved these changes

2023-09-19 11:49 UTC, pieleric commented
I've now rebased against the latest master, which has the changes for the light-in coupling modules. That affects a couples of places. I've also found a few extra places to clean-up.

2023-09-26 08:42 UTC, sneepstefan approved these changes

2023-09-26 11:16 UTC, merged