[feature] Tescan meteor stage implementation
delmic/odemis pull request #2542
Opened 2023-10-11 15:27 UTC by K4rishma

Support Tescan stage translation for Meteor

Major changes:-
- Create Tescan stage movement class in move.py
- Create more support for the rotation and shear for the Linked YZ in actuator.py

2023-10-12 07:46 UTC, pieleric commented
@K4rishma , the changes from Stefan on tescan.py have been merged into master already a month ago. If you do a `git rebase upstream/master` on your branch, this  "extra" commit should automatically disappear. (Or maybe not... if it's an old version of the changes by Stefan, in which case you have to manually drop it).

2023-10-12 07:56 UTC, K4rishma commented
> @K4rishma , the changes from Stefan on tescan.py have been merged into master already a month ago. If you do a `git rebase upstream/master` on your branch, this "extra" commit should automatically disappear. (Or maybe not... if it's an old version of the changes by Stefan, in which case you have to manually drop it).

I was also expecting it to dropped, you are right. The commit hashes are different, that is why git sees it as a new commit, I will manually drop it.

2023-10-26 12:43 UTC, sneepstefan requested changes

2023-11-03 14:47 UTC, sneepstefan approved these changes

2023-11-06 12:52 UTC, pieleric approved these changes

2023-11-06 12:52 UTC, merged