[fix] auto brightness/contrast and histrogram display could sometimes return shifted values
delmic/odemis pull request #2567
Opened 2023-11-16 12:07 UTC by pieleric

This fixes display issues related to the histrogram in the GUI, and should also speed up a little bit the histrogram computation (not that it was really noticeable anyway).
Also makes some test cases pass again.

2023-11-16 16:04 UTC, pieleric commented on src/odemis/acq/stream/_base.py
>                                  mn_p2 = 2 ** int(math.floor(math.log(mn + 1, 2)))
This still causes some issues... when there is only one value, which is a multiple of 256 (mn > mx).

2023-11-21 15:18 UTC, sneepstefan requested changes

2023-11-21 15:18 UTC, sneepstefan commented on src/odemis/acq/stream/_base.py
> +                            mx10 = math.ceil(mx10 / 256) * 256 - 1  # so that the length a multiple of 256
```suggestion
                            mx10 = math.ceil(mx10 / 256) * 256 - 1  # to make sure the length is a multiple of 256
```

2023-11-21 15:18 UTC, sneepstefan commented on src/odemis/util/test/img_test.py
> +        # Hisogram really not the same size: 401px -> bins of 2px -> length of 201px
```suggestion
        # Histogram deliberately not the same size: 401px -> bins of 2px -> length of 201px
```

2023-11-27 13:02 UTC, sneepstefan approved these changes

2023-11-27 22:42 UTC, patrickcleeve2 approved these changes

2023-11-28 14:03 UTC, merged