[CSDM-1103] plugins: new spectrum raw plugin
delmic/odemis pull request #2583
Opened 2023-11-24 16:46 UTC by pieleric

Allows to acquire a spectrum while keeping the raw 2D image with the CCD.
The Y dimension of the CCD is stored as "T" (Time), because the Y dimension is already used for the e-beam position, and also the T dimension allows to directly use the standard Odemis viewer to look at the data (as "temporal spectrum" data).

2023-12-01 01:03 UTC, patrickcleeve2 approved these changes

2023-12-14 12:06 UTC, sneepstefan requested changes

2023-12-14 12:06 UTC, sneepstefan commented on plugins/spectrum_raw.py
> +    def _assembleFinalData(self, n, data):
Find a better name for 'n'?

2023-12-18 16:00 UTC, pieleric commented on plugins/spectrum_raw.py
> +    def _assembleLiveData(self, n, raw_data, px_idx, rep, pol_idx):
That's a copied from the _sync.py. I'd rather keep the same argument names.

2023-12-18 16:57 UTC, pieleric commented
> When I test it with a simulator, I get this warning which is probably not so important: 11:59:58 WARNING stream : Stream Spectrum Raw of unknown order type SpectrumRawSettingsStream Maybe related to this is that the stream name in the stream bar on the left side is not updated accordingly (still named "Temporal Spectrum"). _Edit -> after fully reviewing I noticed this was on purpose._

Yes, that's because the GUI doesn't know this type of stream, which means it doesn't know in which order in the stream panel it should be set. With Python it's probably possible to hack the GUI code from the plugin and avoid this warning... However the actual effect is minimal (the stream is just shown last). I'd rather avoid adding complicated and fragile code just for that.

2023-12-19 08:56 UTC, sneepstefan approved these changes

2023-12-19 09:07 UTC, merged