[TRCL-10] validate SE, CL and EBIC simultaneous acquisition
delmic/odemis pull request #2584
Opened 2023-11-27 08:34 UTC by FCanberk

add test cases with SE, CL and EBIC acquisitions
validate to have SE, CL and EBIC acquisitions simultaneously
remove unnecessary `children` from sparc2 streak cam sim microscope file

2023-11-27 17:48 UTC, pieleric requested changes

2023-11-27 17:48 UTC, pieleric commented on src/odemis/acq/test/stream_test.py
> +        mcs_two = stream.CLSettingsStream("testTWO",
Let's change it to a EBICSettingsStream. Mainly to use that new class, and also because it feels more logical in this test case.

2023-11-28 10:44 UTC, K4rishma approved these changes

2023-11-30 12:58 UTC, pieleric approved these changes

2023-11-30 13:42 UTC, merged