[refactor] odemis gui comp stream.py file
delmic/odemis pull request #2629
Opened 2024-01-19 17:01 UTC by nandishjpatel

[refactor] all the classes earlier in odemis.gui.comp.stream.py have been split into individual python files.

The stream file has been split into stream_bar and stream_panel files. The fastem specific code unrelated to the stream has also been sperated.

2024-01-22 13:42 UTC, pieleric requested changes

2024-01-22 13:42 UTC, pieleric commented on src/odemis/gui/comp/fastem.py
`gui.comp.fastem` sounds too generic, especially compared to the other files like "stream_panel" et al. 
Maybe you could name it `fastem_panel` or  break it into `fastem_project` for the first couple of classes, and then `fastem_calib` for the last 3 classes?

2024-01-22 13:42 UTC, pieleric commented on src/odemis/gui/comp/_constants.py
> +ICON_WIDTH, ICON_HEIGHT = 16, 16
Let's just duplicate these constants in the 2 files they are used. Especially, I can easily imagine that as the implementation diverges these values will be different.

Especially, the advantage is that you can drop this entire file now.

2024-01-22 14:51 UTC, nandishjpatel commented on src/odemis/gui/comp/fastem.py
Can I leave this as it is now? I will give more meaningful naming during VolumeEM GUI development?

2024-01-23 13:02 UTC, pieleric requested changes

2024-01-23 13:02 UTC, pieleric commented on src/odemis/gui/comp/stream_panel.py
> +StreamPeakEvent, EVT_STREAM_PEAK = wx.lib.newevent.NewEvent()
Please move these ones to `odemis.gui.evt` too.

2024-01-23 13:02 UTC, pieleric commented on src/odemis/gui/comp/fastem.py
OK.

2024-01-23 13:19 UTC, tepals approved these changes

2024-01-23 14:18 UTC, pieleric approved these changes

2024-01-23 14:19 UTC, merged