[refactor] odemis gui cont streams.py file
delmic/odemis pull request #2630
Opened 2024-01-19 18:36 UTC by nandishjpatel

[refactor] create a streams subpackage in odemis.gui.cont, all the classes earlier in odemis.gui.cont.streams.py have been split into individual python files under the odemis.gui.cont.streams subpackage.

The refactoring will result in a better file structure.

NOTE: https://github.com/delmic/odemis/pull/2629 needs to be merged first before reviewing this PR

2024-01-22 14:21 UTC, tepals approved these changes

2024-01-23 13:11 UTC, pieleric requested changes

2024-01-23 13:11 UTC, pieleric commented on src/odemis/gui/cont/streams/stream_bar.py
Let's not break too much every class. I'd rather see all the children classes of `StreamBarController` into the same file, here. It's simpler to read the code, as methods are overridden and delegated.

2024-01-23 14:19 UTC, nandishjpatel commented on src/odemis/gui/cont/streams/stream_bar.py
The `stream_bar.py` is already 1056 lines, having all the children classes will add-up more. To read the code, I think one can split the IDE window (one window `stream_bar.py` second window children class). @pieleric what's your final say? I do it.

2024-01-23 14:21 UTC, pieleric commented on src/odemis/gui/cont/streams/stream_bar.py
Please keep all the related classes in a single file.

2024-01-24 09:38 UTC, pieleric requested changes

2024-01-24 09:38 UTC, pieleric commented on src/odemis/gui/cont/streams/__init__.py
No need to create a submodule `streams` . Just place the `stream.py` and `stream_bar` in `odemis.cont`. 
This way, you can write in the tab controllers code:
`from odemis.gui.cont.stream_bar import StreamBarController`

2024-01-24 09:59 UTC, nandishjpatel commented on src/odemis/gui/cont/streams/__init__.py
Done!

2024-01-24 10:12 UTC, pieleric commented
@nandishjpatel , there is a conflict (easy to fix). Would you mind fixing it? Then I will merge.

2024-01-24 10:17 UTC, nandishjpatel commented
> @nandishjpatel , there is a conflict (easy to fix). Would you mind fixing it? Then I will merge.

Thanks! resolved now.

2024-01-24 10:45 UTC, merged