[refactor] odemis.gui.cont.acquisition.py file
delmic/odemis pull request #2635
Opened 2024-01-23 07:25 UTC by nandishjpatel

[refactor] create a acquisition subpackage in odemis.gui.cont, all the classes earlier in odemis.gui.cont.acquisition.py have been split into individual python files under the odemis.gui.cont.acquisition subpackage.

The refactoring will result in a better file structure.

2024-01-23 12:21 UTC, pieleric requested changes

2024-01-23 12:21 UTC, pieleric commented on src/odemis/gui/cont/acquisition/snap_shot.py
Let's name this file `snapshot.py`. No `_`.

2024-01-23 12:21 UTC, pieleric commented on src/odemis/gui/cont/acquisition/fine_align.py
This file has nothing to do with acquisition => move it to `gui.cont`

2024-01-23 12:21 UTC, pieleric commented on src/odemis/gui/cont/acquisition/auto_center.py
This file has nothing to do with acquisition => move it to `gui.cont`

2024-01-23 13:36 UTC, tepals commented on src/odemis/gui/cont/acquisition/fine_align.py
> +from odemis.util import units
```suggestion
import odemis.gui.model as guimod
from odemis import model
from odemis.acq import align
from odemis.gui.comp import popup
from odemis.gui.comp.canvas import CAN_DRAG, CAN_FOCUS
from odemis.gui.util import call_in_wx_main
from odemis.gui.util.widgets import ProgressiveFutureConnector
from odemis.util import units
```

2024-01-24 09:24 UTC, tepals approved these changes

2024-01-24 09:43 UTC, pieleric approved these changes

2024-01-24 09:43 UTC, merged