[feature] New SPARC Mirror actuator interlock plugin
delmic/odemis pull request #2644
Opened 2024-01-30 15:19 UTC by pieleric

Check for interlock affecting the SPARC parabolic mirror. If the interlock is triggered, the
"ENGAGE MIRROR" button is disabled. If the mirror is engaged when the interlock is triggered, the
mirror is automatically parked.

Obviously, it needs a interlock. So add a simulated interlock to a SPARC
simulator. Activate the interlock with:
odemis set-attr bsd-interlock interlockTriggered True

2024-01-30 20:45 UTC, FCanberk approved these changes

2024-02-07 08:46 UTC, sneepstefan requested changes

2024-02-07 08:46 UTC, sneepstefan commented on plugins/sparc_mirror_interlock.py
> +            c.interlockTriggered.subscribe(self._on_interlock_change)
Do you not rather want to unsubscribe here on termination?

2024-02-16 10:40 UTC, sneepstefan approved these changes

2024-02-16 10:57 UTC, merged