[feature] new semnidaq driver: control a SEM via the NI-DAQ API
delmic/odemis pull request #2655
Opened 2024-01-31 10:30 UTC by pieleric

Depends on the "nidaqmx-python" Python wrapper for using the NI-DAQmx API.
For now tested only on a NI PCIe-6361... and also known to not work
yet on older devices like the PCIe-6251.

It supports all features needed for the SECOM and SPARC, with the
exception of the counter detector. Tested succesfully on a real SEM.

It is possible to test it on a computer without an actual card by using
the NI-DAQmx with a simulated DAQ card. Instructions are in the top
comment of semnidaq.py .

Also introduces two microscope files: one to use a real DAQ board, only,
and one to simulate a SPARC using a simulated NI DAQ board.A

2024-02-09 14:27 UTC, FCanberk reviewed
i am doing the new linter's job for this PR: 

please don't forget to add the empty new lines at the end of new files  :grin:

2024-02-12 13:52 UTC, tepals requested changes
I tried to look into everything as much as possible, but I'm sure I missed something. Let me know if there is a specific part or function that you want me to look into in more detail.

2024-02-20 09:19 UTC, pieleric commented on src/odemis/driver/semnidaq.py
> +        :param device: name of the NI DAQ device (ex: "Dev1"). See "nilsdev".
It's a command. I've updated the comment.

2024-02-20 09:22 UTC, pieleric commented on src/odemis/driver/semnidaq.py
> +            self._hwVersion = f"NI {self._nidev.product_type} s/n: {self._nidev.serial_num}"  # Will fail here
Indeed... not very clear. It fails *if it's incorrect* only on line 142. Updated the comment.

2024-02-20 13:12 UTC, pieleric commented on src/odemis/driver/semnidaq.py
> +            width = lim[1] - lim[0]
Not necessarily. But it works in both directions. I think the word is badly picked though, as it implies a positive value. => Changed to `volt_diff`.

2024-02-20 14:04 UTC, pieleric commented on src/odemis/driver/semnidaq.py
> +            raise ValueError(f"multi_detector_min_period must be float, but is {type(multi_detector_min_period)}")
I've adjusted it to just say "a number".

2024-02-20 14:29 UTC, pieleric commented on install/linux/usr/share/odemis/sim/sparc2-nidaq-sim.odm.yaml
> +    role: "brightlight",
With and without quotes are equivalent, as in YAML, strings are automatically detected. It's the same for the classes or the component names. However strings with spaces must be quoted. So we have the habit to always quote the component names. For classes and role, they are not supposed to contain spaces, so it's safe to never quote them. I've cleaned up this microscope file to drop all the quotes from the "role".

2024-02-23 08:48 UTC, tepals approved these changes

2024-02-23 13:16 UTC, merged