[fix] autostig period for idx 0 behaved incorrectly
delmic/odemis pull request #2680
Opened 2024-02-21 12:28 UTC by tepals

For idx 0 even if the autostig period was set to 0 it would still run the extended pre-calibrations. Additionally it should not run for idx 0, only for subsequent indices.

2024-02-21 20:54 UTC, pieleric requested changes

2024-02-21 20:54 UTC, pieleric commented on src/odemis/gui/cont/acquisition/fastem_acq.py
> +                elif idx % autostig_period == 0:
Should just be `else`. It should be clear that there are only 2 cases.

2024-02-27 15:30 UTC, pieleric approved these changes

2024-02-29 05:49 UTC, nandishjpatel approved these changes

2024-02-29 05:59 UTC, merged