[feature][METEOR-727] select the z stream for the Localization z and cancel local…
delmic/odemis pull request #2695
Opened 2024-03-04 07:09 UTC by K4rishma

…ization z

2024-03-04 07:11 UTC, K4rishma commented
Create two separate commits after the review process : one for stream selection and another for allowing cancellation

2024-03-20 08:52 UTC, nandishjpatel commented on src/odemis/acq/align/z_localization.py
> +            if f._task_state == CANCELLED:
Do you want the final sub-future task `stigmator.moveAbs({"rz": 0})` to handle cancel and raise an exception? or this final sub-future should always be executed?

2024-03-20 08:53 UTC, nandishjpatel commented on src/odemis/acq/align/z_localization.py
> +    logging.debug("Canceling localization procedure...")
```suggestion
    logging.debug("Cancelling localization procedure...")
```

2024-03-25 13:25 UTC, pieleric requested changes

2024-04-05 16:40 UTC, K4rishma commented on src/odemis/gui/cont/acquisition/cryo_z_localization.py
> +        # Display order in the "Streams" panel in the Localization Tab
That is correct, if the order of the stream panel streams and menu list streams matches if they are in the same order. I will rectify this.

2024-04-12 10:02 UTC, pieleric requested changes

2024-05-21 13:26 UTC, pieleric approved these changes

2024-05-21 13:27 UTC, merged