[feat] integrate SEM autofocusing in the pre-calibrations
delmic/odemis pull request #2739
Opened 2024-04-18 14:45 UTC by tepals

SEM autofocus has been added to fastem-calibrations and is now integrated in the pre-calibrations.
* A constant has been added to define how often to run SEM autofocusing (every n ROAs).
* The SEM autofocus button in the GUI now points to the new autofocusing ** For SEM autofocus and autocontrastbrightness also disable the button of the autofunction that is running, as these cannot be cancelled

2024-04-18 22:03 UTC, pieleric requested changes

2024-04-18 22:03 UTC, pieleric commented on src/odemis/gui/cont/acquisition/fastem_acq.py
>                  else:
I think here would be clearer to explicitly write:
```suggestion
                if idx > 0:
```

2024-04-18 22:03 UTC, pieleric commented on src/odemis/gui/conf/file.py
> +        self.default.set("acquisition", "autofocus_period", "5")
Could you indicate the unit here in comment (and do the same for the autostig_period). It's in "number of RoA acquisitions", right?

2024-04-22 15:14 UTC, pieleric approved these changes

2024-04-23 04:28 UTC, nandishjpatel commented
@tepals can you add the `se_detector` and `ebeam_focus` components in the unittest [here](https://github.com/tepals/odemis/blob/4b618088a40e11ba322c68bcb1a8501dcd881c66/src/odemis/acq/align/test/fastem_test.py#L75)

2024-04-23 07:23 UTC, tepals commented
> @tepals can you add the `se_detector` and `ebeam_focus` components in the unittest [here](https://github.com/tepals/odemis/blob/4b618088a40e11ba322c68bcb1a8501dcd881c66/src/odemis/acq/align/test/fastem_test.py#L75)?

fixed

2024-04-23 07:29 UTC, nandishjpatel approved these changes

2024-04-23 07:32 UTC, merged