[feat] show pop up when trying to close the GUI
delmic/odemis pull request #2749
Opened 2024-04-29 15:47 UTC by tepals

For the fast-em systems the users requested that they get a pop up when trying to close Odemis. Often it takes some time to set up an acquisition and if then the user accidentally clicks close, they have to redo all of that.

2024-04-29 15:49 UTC, tepals commented
See ticket for screenshot: https://delmic.atlassian.net/browse/SDEV-1863
I now only implemented this for fast-em, but it might also be nice for other GUIs.

2024-04-30 05:10 UTC, patrickcleeve2 approved these changes

2024-05-01 05:55 UTC, nandishjpatel approved these changes

2024-05-01 06:01 UTC, nandishjpatel commented on src/odemis/gui/main.py
> +            result = wx.MessageBox("Do you want close Odemis?", "Confirmation", wx.YES_NO | wx.ICON_QUESTION)
```suggestion
            result = wx.MessageBox("Do you want to close Odemis?", "Confirmation", wx.YES_NO | wx.ICON_QUESTION)
```

2024-05-01 06:29 UTC, pieleric requested changes
Could you implement it the same way as for the METEOR? See cryo chamber tab/query_terminate()

2024-05-15 08:23 UTC, pieleric requested changes
Why not implementing it via `query_terminate()`, like in cryo chamber tab?
BTW, in your current implementation, if there is an acquisition in progress, it will first ask confirmation, then the user answers "Close the window", and then it'll say "Sorry you cannot, because an acquisition is in progress!". That's odd.

2024-05-22 09:45 UTC, tepals commented
@pieleric I now integrated it in  `query_terminate`

2024-05-22 11:34 UTC, pieleric requested changes
Sorry, that's not what I meant. Please add a query_terminate() on the tab controller of the Fastem, which shows the dialogue box.

2024-05-22 11:46 UTC, tepals commented
@pieleric I updated it again, let me know if this is also not what you meant, then we can have a face to face talk about it.

2024-05-22 11:55 UTC, pieleric requested changes
Yes! That's what I meant!
Just minor comments.

2024-05-22 11:55 UTC, pieleric commented on src/odemis/gui/cont/tabs/fastem_main_tab.py
> +        self.main_data = main_data
Not needed?

2024-05-22 11:55 UTC, pieleric commented on src/odemis/gui/cont/tabs/fastem_main_tab.py
> +        Call each tab query_terminate to perform any action prior to termination
Wrong description

2024-05-22 12:17 UTC, pieleric approved these changes

2024-05-22 12:49 UTC, merged