[feature] odemis-start-turret: show notification when starting
delmic/odemis pull request #2773
Opened 2024-05-23 15:03 UTC by pieleric

need to pass --notify, and a notification will appear.
Also allow to pass a specific name of the turret to make it more
user-friendly.

2024-05-24 15:20 UTC, K4rishma commented on scripts/odemis-start-turret.py
> +            notify2.init("Odemis")
Can this line be after line 79 i.e. turning on power control unit such that it can be unified with second if notify on line 80?

2024-05-24 15:20 UTC, K4rishma approved these changes

2024-05-29 07:23 UTC, sneepstefan requested changes

2024-05-29 07:23 UTC, sneepstefan commented on scripts/odemis-start-turret.py
>  from odemis.driver import powerctrl, andorshrk
```suggestion
import logging
import os
import sys
import time

import notify2

from odemis.driver import powerctrl, andorshrk
```

2024-05-29 07:23 UTC, sneepstefan commented on scripts/odemis-start-turret.py
> +        # driver might fail to initialize (but trying again will then work).
Doesn't this refer to the option external/internal powered of the spectrograph? If so I think this comment could be rephrased.

2024-05-31 05:57 UTC, sneepstefan approved these changes

2024-05-31 07:40 UTC, merged