[fix] Add power metadata when using a spectrum stream with a light emitter
delmic/odemis pull request #2821
Opened 2024-07-10 12:34 UTC by sneepstefan

When using a spectrum stream with a light emitter connected which will control the power value of the emitter now this metadata is added to the stream as well.

2024-07-10 22:24 UTC, patrickcleeve2 approved these changes

2024-07-11 06:57 UTC, pieleric requested changes
Normally the mdupdater can do this for you. You just need to put an affects on the light = [Camera, Spectrometer]. Can you check, and if this doesn't work, we can have a deeper look into it.

2024-07-15 09:59 UTC, K4rishma approved these changes

2024-08-08 12:49 UTC, sneepstefan commented
It seems the mdupdater indeed handles this as it should when the affects are correct. However since the stream is paused just before the acquisition starts, the actual power is changed to 0 due to safety choices -> When the stream is not playing the light source should be off.

Will close this PR and make new changes to the code responsible for handling the power VA on the SpectrumSettingsStream.

2024-11-29 17:15 UTC, pieleric commented
Fixed using the right "affects" in the microscope file. Added a test case in PR #2956 .

2024-11-29 17:15 UTC, closed without merging