[fix] adjust streak cam alignment tab when using external spectrograph
delmic/odemis pull request #2835
Opened 2024-07-19 12:52 UTC by pieleric

2024-07-24 09:37 UTC, tepals requested changes

2024-07-24 09:37 UTC, tepals commented on src/odemis/acq/align/autofocus.py
> +    :param align_mode: see Sparc2AutoFocus
If I check `Sparc2AutoFocus` I see the following options for align_mode: `OPM mode, spec-focus or spec-fiber-focus, streak-focus`. However here you also check for a few other modes. Should this docstring be extended, or the docstring for `Sparc2AutoFocus`, or something else?

2024-07-24 09:37 UTC, tepals commented on src/odemis/acq/align/autofocus.py
> +    :param align_mode: see Sparc2AutoFocus
Additionally the docstring for `Sparc2AutoFocus` does not explain what align_mode is, could you update that?

2024-07-24 09:37 UTC, tepals commented on src/odemis/gui/cont/tabs/sparc2_align_tab.py
> +                # Do no enable detector selection, as only the streak-ccd is available
typo: no -> not

2024-08-05 18:09 UTC, patrickcleeve2 approved these changes

2024-08-28 12:36 UTC, tepals approved these changes

2024-08-29 13:36 UTC, merged