[fix] SPARC acquisition issues
delmic/odemis pull request #2839
Opened 2024-07-24 07:23 UTC by pieleric

2024-07-24 09:26 UTC, tepals requested changes

2024-07-24 09:26 UTC, tepals commented on src/odemis/model/_dataflow.py
> +        # number and let the client drop the messages.
can you update the comment to explain what the code below the `return` is for and when it can be uncommented?

2024-07-25 09:58 UTC, nandishjpatel approved these changes

2024-07-26 07:20 UTC, tepals approved these changes

2024-07-27 18:49 UTC, merged