[fix] driver semnidaq: various fixes
delmic/odemis pull request #2869
Opened 2024-09-06 11:06 UTC by pieleric

2024-09-06 13:52 UTC, tmoerkerken requested changes

2024-09-06 13:52 UTC, tmoerkerken commented on src/odemis/driver/test/semnidaq_test.py
> +        # self.counter.data.synchronizedOn(self.counter.softwareTrigger)
There are a few commented out lines in here. Do you want to keep them as reference? We could use git history for that right?

2024-09-06 13:52 UTC, tmoerkerken commented on src/odemis/driver/test/semnidaq_test.py
> +    # @skip("Too long (~ 1h20)")
This doesn't seem right, needs to have "skip" in final code

2024-09-06 13:52 UTC, tmoerkerken commented on src/odemis/driver/test/semnidaq_test.py
> +        # self.scanner.resolution.value = (192, 256)
Use commented values

2024-09-09 07:08 UTC, nandishjpatel approved these changes

2024-09-09 09:44 UTC, tmoerkerken approved these changes

2024-09-09 10:26 UTC, merged