[feat] Introduce more streak-cam automatic protection
delmic/odemis pull request #2886
Opened 2024-09-30 16:04 UTC by pieleric

2024-10-04 05:30 UTC, patrickcleeve2 approved these changes

2024-10-04 06:57 UTC, pieleric commented on src/odemis/acq/stream/_helper.py
> +                        self.streak_unit.shutter.value = True
`shutter = True`  means the shutter gets closed (and stays so) . So, no light anymore.

2024-10-04 07:59 UTC, tmoerkerken requested changes

2024-10-04 07:59 UTC, tmoerkerken commented on src/odemis/gui/cont/tabs/sparc2_align_tab.py
> +                               message="Reset streak camera settings were reset due "
```suggestion
                               message="Streak camera settings were reset due "
```

2024-10-15 10:10 UTC, tmoerkerken approved these changes

2024-10-15 12:33 UTC, merged