[fix] kymera-exchange-turret fall back to direct connection if component not available on current back-end
delmic/odemis pull request #2895
Opened 2024-10-11 11:03 UTC by pieleric

The script can connect to the spectrograph in two ways: either via the
running back-end (based on the role), or directly (based on a serial
number).

If a back-end is available, the script would only try to connect via the
back-end. However, it can be that the current back-end doesn't control
the specific spectrograph. In this case, it shouldn't fail, but just try
via the direct connection.

Note that this doesn't solve *every* case, as if the backend connects to
another spectrograph, it might have also claimed the spectrograph we are
interested in, because that's how the Andor SDK works. In such case, the
only option is to stop the back-end. It's not a big deal, as after
switching the turret, the back-end must be restarted anyway.

2024-10-12 14:40 UTC, tmoerkerken commented
Sorry for closing, the page didn't load fully, and then I accidentally clicked on close since it popped up suddenly. Should be reopened.

2024-10-12 14:43 UTC, tmoerkerken requested changes

2024-10-12 14:43 UTC, tmoerkerken commented on util/kymera-exchange-turret.sh
> +    # Checkk the back-end has the component
Typo
```suggestion
    # Check the back-end has the component
```

2024-10-14 05:39 UTC, nandishjpatel approved these changes

2024-10-16 09:54 UTC, merged