[FIX] Minor issues with auto feature acquisition
delmic/odemis pull request #2918
Opened 2024-10-28 06:59 UTC by patrickcleeve2

Fixes some minor issues with auto acquisition of features
- Z-stack checkbox not correctly implemented
- Add feature name and status to image description to for auto feature acquisition

2024-10-28 07:06 UTC, pieleric requested changes

2024-10-28 07:06 UTC, pieleric commented on src/odemis/driver/actuator.py
> -                 inverted=None, **kwargs):
This is from a separate PR.

2024-10-28 07:58 UTC, patrickcleeve2 commented on src/odemis/driver/actuator.py
> -                 inverted=None, **kwargs):
removed

2024-10-28 13:17 UTC, tepals approved these changes

2024-10-29 06:28 UTC, pieleric approved these changes

2024-10-29 06:28 UTC, merged