[feat] make fastem beam blanking in between fields optional
delmic/odemis pull request #2945
Opened 2024-11-20 10:23 UTC by tepals

For some samples the beam damage is minimal when the beam is left unblanked during stage moves. As beam blanking and unblanking takes ~0.16 s, this feature makes beam blanking optional to increase throughput.

2024-11-20 22:49 UTC, patrickcleeve2 approved these changes

2024-11-20 23:13 UTC, pieleric requested changes

2024-11-20 23:13 UTC, pieleric commented on src/odemis/gui/xmlh/resources/panel_tab_fastem_acqui.xrc
> +                            <label>Turn off beam blanking in between fields</label>
It feels like double negation... which is negated if you don't check the box. It's a little confusing.
How about "Do not blank beam in between fields" or even "Blank beam in between fields" (in which case the check box has to be inverted)?

2024-11-21 16:09 UTC, pieleric approved these changes

2024-11-22 10:59 UTC, merged