[METEOR-1230][fix] store power correctly for each channel in metadata
delmic/odemis pull request #2947
Opened 2024-11-21 00:43 UTC by patrickcleeve2

being tested at customer

2024-11-22 11:03 UTC, K4rishma approved these changes

2024-11-22 11:04 UTC, K4rishma commented
Compared it with master, light power gets correctly updated with/without z stack acquisition, the test cases also pass.

2024-11-25 11:06 UTC, pieleric requested changes

2024-11-25 11:06 UTC, pieleric commented on src/odemis/dataio/tiff.py
> +                                    attrib={"ID": "LightSource:%d" % gdid})
Using just the gdid here is incorrect, as there can be several groups of zstacks. So, something like `did + gdid` would more likely work in every case.

2024-11-26 01:04 UTC, patrickcleeve2 commented on src/odemis/dataio/test/tiff_test.py
>          # create 3 greyscale images with Z stacks of same size
I've updated these, but I can't imagine a scenario for meteor that you can acquire and save two z-stacks with different positions in the same file? Is there something I'm missing?

2024-11-28 07:57 UTC, pieleric approved these changes

2024-11-28 07:57 UTC, merged