[fix] add check if tescan stage moves to the requested position otherwise…
delmic/odemis pull request #2949
Opened 2024-11-22 09:33 UTC by K4rishma

… raise an error

Works on simulator
Tested on hardware

2024-11-25 12:20 UTC, pieleric requested changes
With so much "clean-up" mixed up with the actual change, it would be nicer to have all the clean-up as a separate commit.

2024-11-25 12:20 UTC, pieleric commented on src/odemis/driver/tescan.py
> +        while not isNearPosition(current_pos=current_pos, target_position=target_pos,
If you call this function at the end of the move, it doesn't make sense to keep waiting. Especially, it doesn't seem that the ._position has any chance to update...

2024-12-20 09:57 UTC, nandishjpatel commented on src/odemis/driver/tescan.py
> +        Checks if the current stage position is equal to the given position.
```suggestion
        Checks if the current stage position is near the given position.
```

2024-12-20 10:10 UTC, nandishjpatel approved these changes

2025-01-10 09:38 UTC, K4rishma commented
@pieleric it is ready to review

2025-01-28 08:04 UTC, pieleric requested changes

2025-01-28 08:04 UTC, pieleric commented on src/odemis/driver/tescan.py
> +        """
Please add a :raise: docstring to indicate it will fail if the stage doesn't reach the target position within a given time.

2025-01-28 08:04 UTC, pieleric commented on src/odemis/driver/tescan.py
> +        wait_stage_move = 5  # s
Let's make this an argument (with default value  = 5s). That should make it clearer that the function will time-out.

2025-01-28 08:04 UTC, pieleric commented on src/odemis/driver/tescan.py
> +        Checks if the current stage position is equal to the given position.
It doesn't just *check*, it also *waits*. Please indicate that in the docstring.

2025-01-28 08:04 UTC, pieleric commented on src/odemis/driver/tescan.py
> +            self._checkPosition(pos_before_move, pos, rel=False)
Probably the most important part of this whole change is missing: explain *why* this is needed. If I understand correctly, that's because the stage might fail to move, but there is no way to detect it explicitly, so you need to detect a failure to move by just comparing the requested position to the final position? Or is it also like on the TFS stage, where it can report it's finished moving, but it's not?

2025-02-03 13:44 UTC, K4rishma commented on src/odemis/driver/tescan.py
> +            self._checkPosition(pos_before_move, pos, rel=False)
Added to the comment, It is first option that we need to check explicitly that the stage has moved to the requested position as it does not give any error when the stage fails to move.

2025-02-10 12:43 UTC, pieleric approved these changes

2025-02-10 12:43 UTC, pieleric commented on src/odemis/driver/tescan.py
> +        :param rel: By default False, requested stage position is in absolution position otherwise relative
This function is *always* called with `rel=False`. => drop this argument, and indicate that it's in absolute coordinates all the time.
Also, change the name of `move` to `target_pos`. Then, you can drop the first 4 lines of the function.

2025-02-10 12:43 UTC, pieleric requested changes
.

2025-02-17 11:07 UTC, pieleric approved these changes

2025-02-17 11:08 UTC, merged