[DRAFT][METEOR-1250][FEAT] Add z-stack interpolation for METEOR data
delmic/odemis pull request #2962
Opened 2024-12-04 08:25 UTC by patrickcleeve2

2024-12-09 07:44 UTC, nandishjpatel commented on scripts/meteor-interpolate-data.py
> +import argparse
Can you add the Odemis license in all python files

2024-12-09 07:48 UTC, nandishjpatel commented on scripts/meteor-interpolate-data.py
> +    pixelsize_out: float = None,
```suggestion
    pixelsize_in: Optional[float] = None,
    pixelsize_out: Optional[float] = None,
```

2024-12-09 07:55 UTC, nandishjpatel commented on src/odemis/util/interpolation.py
> +                        pixelsize_out: float = None,
```suggestion
                        pixelsize_in: Optional[float] = None,
                        pixelsize_out: Optional[float] = None,
```

2024-12-09 08:00 UTC, nandishjpatel commented on src/odemis/util/interpolation.py
> +        prefilter=True,  # for better quality
Maybe these 2 can also be function args

2024-12-09 08:09 UTC, nandishjpatel commented on scripts/meteor-interpolate-data.py
> +        choices=["linear", "cubic"],
```suggestion
        choices=["nearest-neighbor", "linear", "cubic"],
```

2024-12-09 08:36 UTC, patrickcleeve2 commented on src/odemis/util/interpolation.py
> +        prefilter=True,  # for better quality
not required for now

2025-01-17 09:25 UTC, pieleric requested changes

2025-01-24 13:45 UTC, pieleric approved these changes

2025-01-24 13:45 UTC, merged