[TRCL-41][feature] Add support for PicoQuant PH330
delmic/odemis pull request #2968
Opened 2024-12-06 17:08 UTC by pieleric

2024-12-19 15:23 UTC, tmoerkerken requested changes
Not done, since it is a lot. But at least here are some preliminary comments.

2024-12-20 13:42 UTC, tmoerkerken requested changes

2025-01-06 16:09 UTC, pieleric commented on install/linux/usr/share/odemis/hwtest/ph330-only.odm.yaml
> +            "Spectrograph": 3, # SR-193 needs a looong time to initialise
On the real system, it's 90s, and this comment comes from such system. Here, it doesn't make sense. => removed.

2025-01-06 16:10 UTC, pieleric commented on src/odemis/driver/picoquant.py
> +        self.softwareTrigger = model.Event()
Good catch! I'll fix the spelling in the manual.

2025-01-09 08:36 UTC, pieleric commented on src/odemis/driver/test/picoquant_test.py
> +                child.triggerLevel.value = -50e-3
That's not useful, because now `triggerLevel` is a VA. The microscope file format supports defining the value of each VA at startup. This means that in practice the user can still define the default value, just not by using the init parameters, but by using the "properties" option. This keeps the code a little simpler.

2025-01-14 08:00 UTC, nandishjpatel commented on src/odemis/driver/picoquant.py
> +        :param daemon:
docstring left for `daemon`?

2025-01-14 08:06 UTC, nandishjpatel commented on src/odemis/driver/picoquant.py
> +            if ("shutter%s" % num) not in shutter_axes.keys():
Maybe use of f-string is more readable for `f"shutter{num}"`

2025-01-14 09:41 UTC, nandishjpatel approved these changes

2025-01-17 12:58 UTC, pieleric commented on src/odemis/driver/test/picoquant_test.py
> +        d = self.dev.data.get()
I added some extra assertions, to use it.

2025-01-17 16:56 UTC, pieleric commented on install/linux/usr/share/odemis/hwtest/ph330-only.odm.yaml
> +    role: photo-detector1,
The more correct answer is "it's complicated" ;-) Sometimes it's really a photo-detector, sometimes not. In practice, this is the role that the GUI expects.

2025-01-17 16:57 UTC, pieleric commented on install/linux/usr/share/odemis/hwtest/ph330-only.odm.yaml
> +        "detector0": "Photon counter sync",
This is explained in the docstring of PH330.

2025-01-17 17:02 UTC, pieleric commented on src/odemis/driver/picoquant.py
> +            channel = None if num == 0 else num - 1
Extended the comment to clarify.

2025-01-22 08:17 UTC, tmoerkerken approved these changes

2025-01-22 10:06 UTC, merged