[SDEV-1945] restructure calibration panel layout
delmic/odemis pull request #2972
Opened 2024-12-12 10:14 UTC by nandishjpatel

[feat] restructured calibration panel layout

Changes
- Calibration 1 also has a box
- Calibration 1, 2, 3 colour are choosen keeping colour blindness in mind
- Individual calibration Run button replaced with individual calibration checkbox and finally a single RUN button to run the checked and enabled calibrations
- Single cancel button to cancel running calibrations

![Screenshot from 2024-12-12 11-10-42](https://github.com/user-attachments/assets/7b05323d-2045-400a-946e-8de56098d6ea)

![Screenshot from 2024-12-12 11-11-20](https://github.com/user-attachments/assets/453a7f56-3c4a-40c5-92e2-c9075aa2039c)

2024-12-13 17:03 UTC, tepals requested changes

2024-12-16 08:12 UTC, nandishjpatel commented on src/odemis/gui/cont/acquisition/fastem_acq.py
> +            logging.debug("Calibrations cancelled.")
The `ProgressiveBatchFuture` is cancelled when a calibration raises an exception or is cancelled, so no need

2024-12-16 08:15 UTC, nandishjpatel commented on src/odemis/gui/cont/acquisition/fastem_acq.py
> +        :param calibration: (FastEMCalibration) The calibration which is finished.
It's all happening here in `ProgressiveBatchFuture`

https://github.com/delmic/odemis/blob/dd5d4cf75cdcf5fddd188f19127536d4cbdd8525/src/odemis/model/_futures.py#L573

https://github.com/delmic/odemis/blob/dd5d4cf75cdcf5fddd188f19127536d4cbdd8525/src/odemis/model/_futures.py#L599

2025-01-06 12:35 UTC, tepals approved these changes

2025-01-06 12:51 UTC, tepals commented
@nandishjpatel can you squash the first two commits ([feat] and [update]) so we can merge?

2025-01-06 13:11 UTC, nandishjpatel commented
> @nandishjpatel can you squash the first two commits ([feat] and [update]) so we can merge?

Done :)

2025-01-07 09:08 UTC, merged