[NSRPARMA-52]  [feature] Ephemeron MightyEBIC support
delmic/odemis pull request #2974
Opened 2024-12-12 16:56 UTC by pieleric

Special driver for the digital connection with the Ephemeron MightyEBIC detector. It requires to be specifically connected from the "pixel" trigger of the semnidaq driver to the EBIC controller via a TTL signal. Then, this driver allows to setup the (remote) control computer of the MightyEBIC specifically for a given acquisition, and receive the EBIC signal digitally.

In addition to the driver, it also introduces a few tweaks to the SPARC synchronized acquisition in order to handle the slightly unusual behaviour of this detector.

2024-12-17 14:35 UTC, tmoerkerken requested changes

2024-12-17 14:35 UTC, tmoerkerken commented on src/odemis/driver/ephemeron.py
> +        # If some incorrect paramaters are sent, it returns an int <= 0.
```suggestion
        # If some incorrect parameters are sent, it returns an int <= 0.
```

2024-12-17 14:35 UTC, tmoerkerken commented on src/odemis/driver/ephemeron.py
> +            delay)
This way of doing multiline parameters, without trailing comma and with closing bracket on same line as last argument, is not the best practice for minimal git diffs (when adding or removing arguments later). However, this approach is prevalent throughout the codebase.

2024-12-17 14:35 UTC, tmoerkerken commented on src/odemis/driver/ephemeron.py
> +        Note: this function can be called several times, and the data will still be available.
This statement could be verified with a unit test

2025-01-10 09:37 UTC, tepals requested changes

2025-01-10 09:37 UTC, tepals commented on src/odemis/driver/test/ephemeron_test.py
> +        print(self.ebic_det.dwellTime.range)
leftover from debugging?

2025-01-10 09:37 UTC, tepals commented on src/odemis/driver/test/ephemeron_test.py
> +            # set the resolution of the region of acquisition to 140 x 100, force it non-squared
for both cases it is not 140x100, right?

2025-01-10 09:37 UTC, tepals commented on src/odemis/driver/test/ephemeron_test.py
> +                res = (100 + i, 100)
why not always use the smaller resolution?

2025-01-10 09:37 UTC, tepals commented on src/odemis/driver/test/ephemeron_test.py
> +            logging.debug("Expected duration for %s px @ %s s: %s s", res, act_dt,
why not make an assert that the expected duration is close to the actual duration? What is the use of this log?

2025-01-10 09:37 UTC, tepals commented on src/odemis/driver/test/ephemeron_test.py
> +        Take the res (4096, 3072) of the e-beam as resolution to scan.
from this description it reads like you want to test if a timeout exception is fired, or at least that the acquisition stops before the very large acquisition is done. But the code looks very different. What is the purpose of this test?

2025-01-27 17:06 UTC, pieleric commented on src/odemis/driver/ephemeron.py
> +        self._shape = MAX_RESOLUTION + (2.0 ** 64,)
Indeed, this is not to create an array, but just to give some information about the detector. The first two values are X & Y dimensions, and the third one is the bit depth.

Good catch about the comment using 11bits instead of 12. I'll update this comment (separately).

2025-01-27 17:09 UTC, pieleric commented on src/odemis/driver/ephemeron.py
> +        See _calculate_dwell_time()
Indeed, this is a wrapper for the Ephemeron server. That's why I use the same names. I'll duplicate the documentation of the parameters, to make it easier to read though.

2025-01-27 21:57 UTC, pieleric commented on install/linux/usr/share/odemis/sim/sparc2-ephemeron-sim.odm.yaml
> +        scan_active_delay: 1.e-3,  # s, time to wait between setting "external" and starting to scan
These TODOs are left-over from the original file, due to copy-paste. They are meaningless here, on a simulator. I'll drop them.

2025-01-27 23:14 UTC, pieleric commented on src/odemis/driver/ephemeron.py
> +        :return: dwell time in μs
I want to keep it a direct wrapper to the function provided by the server. The server returns µs.

2025-01-27 23:17 UTC, pieleric commented on src/odemis/driver/ephemeron.py
> +        req_dt_us = req_dt * 1e6
The server returns values in µs. So all the times in this function are in µs.

2025-01-27 23:18 UTC, pieleric commented on src/odemis/driver/ephemeron.py
> +        :param channels: The number of channels used simultaneously. The server will only use the first N.
Yes, the server names this "channels", hence I keep the same name. I agree it's odd.

2025-01-27 23:25 UTC, pieleric commented on src/odemis/driver/ephemeron.py
> +        :return: p_fast, p_slow, channels pixels of the scan result
Just "p_fast, p_slow and channels". I've dropped the confusing text about pixels.

2025-01-27 23:30 UTC, pieleric commented on src/odemis/driver/ephemeron.py
> +        :param parent:
It's more I have no idea, so I skipped it :wink: 
Well, it's some required argument for asyncua. Looking at the doc, it seems it's the NodeId corresponding to the UA Node that correspond to method.

2025-02-17 15:24 UTC, pieleric commented on src/odemis/driver/test/ephemeron_test.py
> +        # TODO: it seems the default of the server is to limit messages to 100Mb, which is just enough
It's not a bug in the odemis driver, but a potential issue on the server side. I've let Ephemeron know. That's the best we can do.

2025-02-17 15:28 UTC, pieleric commented on src/odemis/driver/test/ephemeron_test.py
> +        self.assertEqual(da.shape[::-1], self.ebic_det.resolution.value)
Yes, the point is just to test a very large resolution. I've updated the test docstring. If the data is bigger that the maximum message size in the server, it'll probably fail. So it's a useful test!

2025-02-17 15:29 UTC, pieleric commented on src/odemis/driver/ephemeron.py
> +        Note: this function can be called several times, and the data will still be available.
Yes, but that's the server API. I don't plan to test the server, because that's Ephemeron's job :wink:

2025-02-17 15:43 UTC, pieleric commented on src/odemis/acq/stream/_helper.py
> +        # We could try to call _restart_acquisition()... but for now it's simpler/safer to just not do it.
I just bit the bullet, and implemented the function fully.

2025-02-17 15:45 UTC, pieleric commented on src/odemis/acq/stream/_helper.py
> +        # Increase the dwell time until it's larger
larger than the detector dwell time. I've updated the comment.

2025-02-17 16:12 UTC, pieleric commented on src/odemis/driver/test/ephemeron_test.py
> +        expected_duration = res[0] * res[1] * act_dt_ebeam  * 1.1
Here, the 1.1 is to account for extra timing during the scanning, like the flyback, and getting the scanner ready. So that it's *really* the time the scan will take.
The 1.5 is just timeout margin. 
Added some comments.

2025-02-17 16:17 UTC, pieleric commented on src/odemis/driver/test/ephemeron_test.py
> +                res = (100 + i, 100)
I want to try larger resolutions too. Hence, a "not too small" resolution when the dwell time is short.

2025-02-17 16:21 UTC, pieleric commented on src/odemis/driver/test/ephemeron_test.py
> +            logging.debug("Expected duration for %s px @ %s s: %s s", res, act_dt,
The long acquisitions can take ~20s, so it's nice to know when looking at the test cases that something is happening.
I'll add a check for the acquisition time. It's a bit tricky with the real hardware, as it depends on some external factor, but there is a minimum duration that is easy to check.

2025-02-17 16:23 UTC, pieleric commented on src/odemis/driver/test/ephemeron_test.py
> +        Take the res (4096, 3072) of the e-beam as resolution to scan.
This description was outdated, I've fixed it.

2025-02-17 16:25 UTC, pieleric commented on src/odemis/driver/test/ephemeron_test.py
> +        self.ebic_data.metadata[model.MD_PIXEL_SIZE] = self.ebeam_data.metadata[model.MD_PIXEL_SIZE]
It is the basic version of what the real acquisition does. It just check that the data can be stored.

2025-02-17 17:13 UTC, tepals approved these changes

2025-02-18 10:11 UTC, tmoerkerken approved these changes

2025-02-20 16:46 UTC, merged