[fix] xt_client: shouldn't provide dwellTime when there is no detector
delmic/odemis pull request #2976
Opened 2024-12-13 16:18 UTC by pieleric

When xt_client is used as a "beam control" in addition to the external
scan board, it doesn't make sense to provide access to the (internal)
dwell time.
=> Only provide .dwellTime if there is a detector child.

2024-12-13 16:23 UTC, tepals approved these changes

2024-12-19 02:55 UTC, patrickcleeve2 commented
I don't really agree with this change here (or on the other client PR), there are times where you would want to control the dwell time independently of detector presence. For example, you can repeatedly scan the SEM to discharge the sample without acquiring, or for FIB milling.

2025-01-06 08:31 UTC, patrickcleeve2 requested changes

2025-01-06 08:31 UTC, patrickcleeve2 commented on src/odemis/driver/xt_client.py
> -        dwell_time_info = self.parent.dwell_time_info()
https://github.com/delmic/odemis/pull/2976#issuecomment-2552670083

2025-01-08 10:48 UTC, pieleric commented
> I don't really agree with this change here (or on the other client PR), there are times where you would want to control the dwell time independently of detector presence. For example, you can repeatedly scan the SEM to discharge the sample without acquiring, or for FIB milling.

I agree that on a (FIB)SEM, it's some time useful to scan the beam without actually acquiring any data. 
However, right now, in Odemis, with the current backend API, it's not possible to request a scan without having a detector. The only way to scan is to call `data.get()` or `data.subscribe()`. So no detector means no scan. 
Technically, it's probably possible to directly call the xt-adapter functions by calling their wrapper on SEM component, but that's not how the back-end is supposed to be used. Clients should only use the backend API, not other functions on the component, and the SEM component has typically no role, because it's not supposed to be used directly.
The right way would be to extend the backend API. I think either we could introduce a "dummy" detector for "blind scanning", or have a DataFlow directly on the scanner component (called something like `nodata` or `scan`...).

2025-01-08 22:33 UTC, patrickcleeve2 approved these changes

2025-01-09 08:22 UTC, merged