[SDEV-1916] fix pre calibration failure stops the acquisition
delmic/odemis pull request #2985
Opened 2024-12-20 08:47 UTC by nandishjpatel

NOTE: This PR depends on https://github.com/delmic/odemis/pull/2972

[feat] allow skipping roa acquisition in case of failure
    
Updates:
- The status text in the ROA window of the project tree will show "Open", "Skipped", "Failed" and respective colour
- Added autostigmation and autofocus period in the Acquisition panel; previously it was in the acquisition.config file
- Added a checkbox `Stop acquisition on failure` which helps is skipping roa acquisition in case of failure
    
![Screenshot from 2024-12-20 09-37-59](https://github.com/user-attachments/assets/ee1976df-dd03-4913-8a22-fa2d6318fb39)

Cancelled
![Screenshot from 2024-12-20 09-40-53](https://github.com/user-attachments/assets/d03911d3-2546-48a7-af28-8f83da108e87)

Stop acquisition on failure checked (Exception is raised in autostigmation)
![Screenshot from 2024-12-20 09-44-16](https://github.com/user-attachments/assets/898f803e-cc49-4a13-a60b-9391d1f45691)

Stop acquisition on failure un-checked (Exception is raised in autostigmation)
![Screenshot from 2024-12-20 09-46-38](https://github.com/user-attachments/assets/93859252-349f-4c19-8721-a53163a9afa0)

2025-01-08 09:38 UTC, tepals commented
@nandishjpatel can you resolve the conflicts in this PR?

2025-01-08 11:32 UTC, nandishjpatel commented
> @nandishjpatel can you resolve the conflicts in this PR?

Done :)

2025-01-13 08:29 UTC, nandishjpatel commented on src/odemis/acq/fastem.py
> +                exception = ROASkipped(f"Skipped the ROA {self._roa.shape.name.value}")
All ROAs `ProgressiveFuture` are run in a `ProgressiveBatchFuture`. If any `ProgressiveFuture` raises an exception inside the `ProgressiveBatchFuture` all subsequent `ProgressiveFuture` will be cancelled. That's why I don't raise the `ROASkipped` and just return it to be later handled for the project tree status.

See here: https://github.com/delmic/odemis/blob/0c0ea725ffdb07b214fa501d93beffd3f44f03a8/src/odemis/model/_futures.py#L568

2025-01-13 08:30 UTC, nandishjpatel commented on src/odemis/acq/fastem.py
> +        super().__init__(message)
Agree, will add the reason to the message and then log it as well

2025-01-24 13:08 UTC, tepals approved these changes

2025-03-06 16:32 UTC, pieleric requested changes
Looks good. Just very minor comments.

2025-03-06 16:32 UTC, pieleric commented on src/odemis/acq/fastem.py
> +        super().__init__(message)
If you just call `super()`, it should be equivalent to to just write:
```suggestion
class ROASkipped(Exception):
    pass
```

2025-03-06 16:32 UTC, pieleric commented on src/odemis/acq/fastem.py
> +                logging.warning("%s", exception)
This drops the whole backtrace. Although the acquisition continues, it might be quite valuable to know the context of the failure.  => add a `exc_info=True` here too.

2025-03-06 16:32 UTC, pieleric commented on src/odemis/acq/fastem.py
> +                    f"Skipped the ROA {self._roa.shape.name.value} due to acquisition failure with exception: {ex}"
You can make the message a little shorter:
```suggestion
                    f"Skipped the ROA {self._roa.shape.name.value} due to acquisition failure: {ex}"
```

2025-03-10 08:13 UTC, pieleric approved these changes

2025-03-10 08:14 UTC, merged