[CSDM-1083] FPLM CL spot overlay
delmic/odemis pull request #2986
Opened 2024-12-20 14:40 UTC by tmoerkerken

2025-01-10 14:23 UTC, tepals requested changes

2025-01-10 14:23 UTC, tepals commented on src/odemis/gui/cont/tabs/sparc2_align_tab.py
> +            # Change binning to differentiate from other stream
You've now set both binnings to `(2, 2)` how can you differentiate?

2025-01-10 14:23 UTC, tepals commented on src/odemis/gui/cont/tabs/sparc2_align_tab.py
> +            self._ccd_stream.image.subscribe(self._onNewMoI)
Is it correct that you use `self._ccd_spe` on line 288 and `self._ccd_stream` on line 289?

2025-01-10 14:23 UTC, tepals commented on src/odemis/gui/cont/tabs/sparc2_align_tab.py
> +            if "light-in-align" in tab_data.align_mode.choices :
```suggestion
            if "light-in-align" in tab_data.align_mode.choices:
```

2025-01-10 14:23 UTC, tepals commented on src/odemis/gui/cont/tabs/sparc2_align_tab.py
> +            # Enforce auto beam blanking when available
It feels a bit strange that you are enforcing the blanker, but then setting it to automatic, instead of always blanking. Is that correct?

2025-01-10 14:23 UTC, tepals commented on src/odemis/gui/model/tab_gui_data.py
> +            and main.mirror.name in main.light_aligner.affects.value
since this is the third time you do this check, does it make sense to have this in a function somewhere? Something like `check_is_fplm`?

2025-01-13 12:44 UTC, tmoerkerken commented on src/odemis/gui/model/tab_gui_data.py
> +            and main.mirror.name in main.light_aligner.affects.value
That is a good one, and I actually discussed this with Éric already a little bit at one point. I'd like to actually, but these are heuristics and not total proof that it is an FPLM module (similar to ELIM and SFLM). Maybe we can come up with a variable name that reflects this, or at least at a comment at instantiation.

Now that I look at this code, I see how it can fail when there is no light aligner available (and no mirror, although that would be surprising for a SPARC system), so I need to improve it anyway.

2025-01-23 13:07 UTC, tmoerkerken commented on src/odemis/acq/stream/_static.py
> +            return raw
If `self.raw` indeed is a DataArray as documented, then we cannot do a truth check like that at this stage, we will get `ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()`. I will try to rewrite it/document it, so it becomes more clear.

2025-01-23 15:07 UTC, tmoerkerken commented on src/odemis/gui/cont/tabs/sparc2_align_tab.py
> +            # Enforce auto beam blanking when available
I don't want to "mess" with the auto blanking behavior (assuming it works). If I set it to "True" then there is no automatic mode anymore.

2025-01-23 15:08 UTC, tmoerkerken commented on src/odemis/gui/cont/tabs/sparc2_align_tab.py
> +            # Change binning to differentiate from other stream
I had that difference earlier for debugging purposes. In real life, the data should be a lot more distinct than on the simulator. The comment should go.

2025-01-23 15:13 UTC, tmoerkerken commented on src/odemis/gui/cont/tabs/sparc2_align_tab.py
> +            self._ccd_stream.image.subscribe(self._onNewMoI)
Yes, it's the same as before (with the difference that the _ccd_stream variable now is being stored on self). _ccd_spe is the stream panel that is updated when the detector data changes.

2025-01-24 13:29 UTC, pieleric requested changes

2025-01-24 13:29 UTC, pieleric commented on src/odemis/gui/cont/tabs/sparc2_align_tab.py
> +    def enforce_blanker(self):
Add a docstring to explain what this does.

2025-01-24 13:29 UTC, pieleric commented on src/odemis/gui/cont/tabs/sparc2_align_tab.py
> +            # Enforce auto beam blanking when available
I think this does what you want... but it's really not obvious by looking at the code.
What it does now is: 
* if the blanker doesn't support "automatic mode" => force e-beam blanker (that's easy to understand)
* if the blanker supports "automatic mode" (most of the systems do), then set it to automatic (which is typically already the current state). That will work *because* `_on_ccd_stream_play()` automatically disables the SEM spot stream when the 2 new align modes are selected (because the `_ccd_stream_light` stream is used, so the others streams are not active). 

This needs to be explained in a comment! I think also the docstring should explain that it'll "enforce" the blanker, assuming that the SEM stream is not playing. (in general, that's very important assumption).

2025-01-24 13:29 UTC, pieleric commented on src/odemis/gui/cont/tabs/sparc2_align_tab.py
> +            self.enforce_blanker()
Probably in every other modes, you need to unblank the beam, if it was blanked here. (Otherwise, the beam will stay blank all all modes).

2025-01-24 13:29 UTC, pieleric commented on src/odemis/acq/path.py
> +               'streak-focus', 'light-in', 'light-in-align', 'light-in-align-ar',
`'light-in'` doesn't seem to be used anywhere -> drop.
`'light-in-align-ar'` should be defined above in `SPARC2_MODES`. Otherwise, going to that mode will leave the optical path as-is (and you shouldn't rely on that what is the current state of the hardware).

2025-01-24 13:29 UTC, pieleric commented on src/odemis/acq/path.py
> +               'streak-focus', 'light-in', 'light-in-align', 'light-in-align-ar',
Please add a test case in `path_test` that goes to `light-in-align-ar` mode.

2025-01-24 13:36 UTC, pieleric commented on src/odemis/gui/cont/tabs/sparc2_align_tab.py
> +        self._blanker = None
Please see line ~559 `if main_data.ebeam_blanker:` . If one was to read the code now, he'd be quite confused. Can you add a comment above this code block (line 559) that the "ebeam_blanker" and the `ebeam.blanker` are not the same thing. The ebeam_blanker is a dedicated hardware for fast blanking (and typically used for pulsed e-beam). The `ebeam.blanker` is just the standard (& slow) blanker.

2025-01-27 10:26 UTC, tmoerkerken commented on src/odemis/acq/stream/_static.py
> +            return raw
I tried to explain it better with typing, docstrings, comments and slight re-organization of the code.

2025-01-27 15:41 UTC, tmoerkerken commented on src/odemis/acq/path.py
> +               'streak-focus', 'light-in', 'light-in-align', 'light-in-align-ar',
Removed light-in and light-in-align-ar. I reuse light-in-align now

2025-01-27 15:41 UTC, tmoerkerken commented on src/odemis/acq/path.py
> +               'streak-focus', 'light-in', 'light-in-align', 'light-in-align-ar',
Not necessary since I reuse existing path

2025-02-11 16:19 UTC, tepals requested changes

2025-02-11 18:04 UTC, tmoerkerken commented on src/odemis/gui/cont/tabs/sparc2_align_tab.py
> +        gb_sizer.Layout()
This one is not so obvious. Let me try to explain:
Just for the FPLM module, we change the text of the LIGHT IN mode to LIGHT IN SPOT at runtime (to differentiate it from LIGHT IN AR). The mode is identical to the original light in mode, so that is why I opted for not adding another separate align mode. 

But when changing text like that (after initial rendering), the size property reflects the old text. I need a Layout() call to get the button sizes for the updated text. In the end everything is positioned and I don't necessarily need another Layout() call.

2025-03-19 13:52 UTC, tmoerkerken commented on src/odemis/gui/cont/tabs/sparc2_align_tab.py
> +            logging.warning('Make sure the e-beam is blanked manually')
Removed it

2025-03-19 13:52 UTC, tmoerkerken commented on src/odemis/gui/cont/tabs/sparc2_align_tab.py
> +        gb_sizer.Layout()
I added a comment to clarify

2025-04-03 13:36 UTC, tepals approved these changes

2025-04-04 16:09 UTC, pieleric approved these changes

2025-04-04 16:09 UTC, pieleric commented on src/odemis/gui/cont/tabs/sparc2_align_tab.py
> +                                                  add_to_view=True)
looks good to me.

2025-04-04 16:10 UTC, merged